music_directory    "/mnt/music"
playlist_directory "/mnt/music"
db_file            "/var/lib/mpd/tag_cache"
log_file           "/var/log/mpd/mpd.log"
pid_file           "/run/mpd/pid"
state_file         "/var/lib/mpd/state"
sticker_file       "/var/lib/mpd/sticker.sql"

user               "mpd"
bind_to_address    "any"

input {
        plugin     "curl"
}

input {
        enabled    "no"
        plugin     "qobuz"
}

input {
        enabled    "no"
        plugin     "tidal"
}

decoder {
        plugin     "hybrid_dsd"
        enabled    "no"
}

audio_output {
        type       "alsa"
        name       "Беспроводные наушники"
        device     "bluealsa:DEV=FF:49:11:E5:2E:00,PROFILE=a2dp"
        mixer_type "software"
}

filesystem_charset   "UTF-8"
