wireplumber.profiles = {
        main = {
                monitor.bluez.seat-monitoring = disabled
        }
}

wireplumber.settings = {
        "default.clock.min-quantum" = 2048
        "default.clock.max-quantum" = 8192
        "default.clock.quantum" = 2048
        "default.clock.rate" = 44100
}

monitor.bluez.properties = {
   "bluez5.a2dp.latency-offset" = 4000
   "bluez5.sbc.sco.packetsize" = 128
}
